import {
  BarChart3,
  Boxes,
  Building2,
  CreditCard,
  FileText,
  FolderTree,
  Globe,
  House,
  Images,
  LayoutGrid,
  Megaphone,
  Package,
  PenLine,
  Rss,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Store,
  UserPen,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { AreaKey } from "@storevia/tenancy/business-types";

// One icon per destination, all Lucide at the shared stroke (ICON_STROKE).
export const NAV_ICONS: Record<
  AreaKey | "stores" | "members" | "organisation" | "billing" | "security",
  LucideIcon
> = {
  home: House,
  orders: ShoppingBag,
  products: Package,
  inventory: Boxes,
  customers: Users,
  website: Globe,
  pages: FileText,
  posts: PenLine,
  categories: FolderTree,
  authors: UserPen,
  projects: LayoutGrid,
  blog: Rss,
  media: Images,
  marketing: Megaphone,
  analytics: BarChart3,
  settings: Settings,
  stores: Store,
  members: Users,
  organisation: Building2,
  billing: CreditCard,
  security: ShieldCheck,
};
