-- Milestone 2: plans, entitlements, subscriptions (ADR-0009 refined by ADR-0022).
-- Part 1 is generated by `prisma migrate diff`; part 2 adds reference features,
-- constraints, RLS and grants that Prisma cannot express.

-- =============================================================================
-- Part 1: tables (generated)
-- =============================================================================
-- CreateEnum
CREATE TYPE "PlanStatus" AS ENUM ('ACTIVE', 'LEGACY', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "BillingInterval" AS ENUM ('MONTH', 'YEAR');

-- CreateEnum
CREATE TYPE "BillingProviderKey" AS ENUM ('MOCK', 'RAZORPAY', 'STRIPE');

-- CreateEnum
CREATE TYPE "FeatureType" AS ENUM ('BOOLEAN', 'LIMIT', 'CONFIGURATION');

-- CreateEnum
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "SubscriptionSource" AS ENUM ('MANUAL', 'MOCK', 'PAYMENT_PROVIDER');

-- CreateEnum
CREATE TYPE "InboundWebhookStatus" AS ENUM ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'IGNORED');

-- CreateTable
CREATE TABLE "Plan" (
    "id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" "PlanStatus" NOT NULL DEFAULT 'ACTIVE',
    "isPublic" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "trialDays" INTEGER NOT NULL DEFAULT 14,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Plan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlanPrice" (
    "id" UUID NOT NULL,
    "planId" UUID NOT NULL,
    "interval" "BillingInterval" NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "amount" BIGINT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PlanPrice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Feature" (
    "id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "type" "FeatureType" NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "defaultEnabled" BOOLEAN NOT NULL DEFAULT false,
    "defaultLimit" BIGINT,
    "defaultUnlimited" BOOLEAN NOT NULL DEFAULT false,
    "defaultConfig" JSONB,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Feature_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlanFeature" (
    "planId" UUID NOT NULL,
    "featureId" UUID NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "limit" BIGINT,
    "unlimited" BOOLEAN NOT NULL DEFAULT false,
    "config" JSONB,

    CONSTRAINT "PlanFeature_pkey" PRIMARY KEY ("planId","featureId")
);

-- CreateTable
CREATE TABLE "OrganisationFeatureOverride" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "featureId" UUID NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    "limit" BIGINT,
    "unlimited" BOOLEAN NOT NULL DEFAULT false,
    "config" JSONB,
    "reason" TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ(3),
    "createdById" UUID,
    "updatedById" UUID,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "OrganisationFeatureOverride_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BillingCustomer" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "provider" "BillingProviderKey" NOT NULL,
    "providerCustomerId" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BillingCustomer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subscription" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "planId" UUID NOT NULL,
    "status" "SubscriptionStatus" NOT NULL,
    "source" "SubscriptionSource" NOT NULL,
    "provider" "BillingProviderKey",
    "providerSubscriptionId" TEXT,
    "billingInterval" "BillingInterval",
    "startedAt" TIMESTAMPTZ(3) NOT NULL,
    "trialStartsAt" TIMESTAMPTZ(3),
    "trialEndsAt" TIMESTAMPTZ(3),
    "currentPeriodStart" TIMESTAMPTZ(3),
    "currentPeriodEnd" TIMESTAMPTZ(3),
    "expiresAt" TIMESTAMPTZ(3),
    "cancelledAt" TIMESTAMPTZ(3),
    "pastDueSince" TIMESTAMPTZ(3),
    "graceEndsAt" TIMESTAMPTZ(3),
    "endedAt" TIMESTAMPTZ(3),
    "providerSyncedAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SubscriptionEvent" (
    "id" UUID NOT NULL,
    "subscriptionId" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "source" "SubscriptionSource" NOT NULL,
    "fromStatus" "SubscriptionStatus",
    "toStatus" "SubscriptionStatus",
    "fromPlanId" UUID,
    "toPlanId" UUID,
    "actorType" "AuditActorType" NOT NULL,
    "actorId" UUID,
    "reason" TEXT,
    "note" TEXT,
    "providerEventId" TEXT,
    "requestId" TEXT,
    "data" JSONB,
    "occurredAt" TIMESTAMPTZ(3) NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SubscriptionEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BillingWebhookEvent" (
    "id" UUID NOT NULL,
    "provider" "BillingProviderKey" NOT NULL,
    "providerEventId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "status" "InboundWebhookStatus" NOT NULL DEFAULT 'RECEIVED',
    "organisationId" UUID,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "outcome" TEXT,
    "lastError" TEXT,
    "payload" JSONB NOT NULL,
    "receivedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMPTZ(3),

    CONSTRAINT "BillingWebhookEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UsageCounter" (
    "organisationId" UUID NOT NULL,
    "featureId" UUID NOT NULL,
    "scopeKey" TEXT NOT NULL DEFAULT '',
    "period" TEXT NOT NULL DEFAULT 'all',
    "value" BIGINT NOT NULL DEFAULT 0,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "UsageCounter_pkey" PRIMARY KEY ("organisationId","featureId","scopeKey","period")
);

-- CreateIndex
CREATE UNIQUE INDEX "Plan_key_key" ON "Plan"("key");

-- CreateIndex
CREATE INDEX "PlanPrice_planId_idx" ON "PlanPrice"("planId");

-- CreateIndex
CREATE UNIQUE INDEX "Feature_key_key" ON "Feature"("key");

-- CreateIndex
CREATE INDEX "PlanFeature_featureId_idx" ON "PlanFeature"("featureId");

-- CreateIndex
CREATE INDEX "OrganisationFeatureOverride_featureId_idx" ON "OrganisationFeatureOverride"("featureId");

-- CreateIndex
CREATE UNIQUE INDEX "OrganisationFeatureOverride_organisationId_featureId_key" ON "OrganisationFeatureOverride"("organisationId", "featureId");

-- CreateIndex
CREATE UNIQUE INDEX "BillingCustomer_organisationId_provider_key" ON "BillingCustomer"("organisationId", "provider");

-- CreateIndex
CREATE UNIQUE INDEX "BillingCustomer_provider_providerCustomerId_key" ON "BillingCustomer"("provider", "providerCustomerId");

-- CreateIndex
CREATE INDEX "Subscription_organisationId_status_idx" ON "Subscription"("organisationId", "status");

-- CreateIndex
CREATE INDEX "Subscription_planId_idx" ON "Subscription"("planId");

-- CreateIndex
CREATE UNIQUE INDEX "Subscription_id_organisationId_key" ON "Subscription"("id", "organisationId");

-- CreateIndex
CREATE UNIQUE INDEX "Subscription_provider_providerSubscriptionId_key" ON "Subscription"("provider", "providerSubscriptionId");

-- CreateIndex
CREATE INDEX "SubscriptionEvent_subscriptionId_occurredAt_idx" ON "SubscriptionEvent"("subscriptionId", "occurredAt");

-- CreateIndex
CREATE INDEX "SubscriptionEvent_organisationId_occurredAt_idx" ON "SubscriptionEvent"("organisationId", "occurredAt");

-- CreateIndex
CREATE INDEX "BillingWebhookEvent_status_receivedAt_idx" ON "BillingWebhookEvent"("status", "receivedAt");

-- CreateIndex
CREATE INDEX "BillingWebhookEvent_organisationId_receivedAt_idx" ON "BillingWebhookEvent"("organisationId", "receivedAt");

-- CreateIndex
CREATE UNIQUE INDEX "BillingWebhookEvent_provider_providerEventId_key" ON "BillingWebhookEvent"("provider", "providerEventId");

-- CreateIndex
CREATE INDEX "UsageCounter_featureId_idx" ON "UsageCounter"("featureId");

-- AddForeignKey
ALTER TABLE "PlanPrice" ADD CONSTRAINT "PlanPrice_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlanFeature" ADD CONSTRAINT "PlanFeature_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlanFeature" ADD CONSTRAINT "PlanFeature_featureId_fkey" FOREIGN KEY ("featureId") REFERENCES "Feature"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrganisationFeatureOverride" ADD CONSTRAINT "OrganisationFeatureOverride_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrganisationFeatureOverride" ADD CONSTRAINT "OrganisationFeatureOverride_featureId_fkey" FOREIGN KEY ("featureId") REFERENCES "Feature"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BillingCustomer" ADD CONSTRAINT "BillingCustomer_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SubscriptionEvent" ADD CONSTRAINT "SubscriptionEvent_subscriptionId_organisationId_fkey" FOREIGN KEY ("subscriptionId", "organisationId") REFERENCES "Subscription"("id", "organisationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UsageCounter" ADD CONSTRAINT "UsageCounter_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UsageCounter" ADD CONSTRAINT "UsageCounter_featureId_fkey" FOREIGN KEY ("featureId") REFERENCES "Feature"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- =============================================================================
-- Part 2: hand-written (ADR-0022)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 2.1 Entitlement values must fit the feature type. One definition shared by
-- Feature defaults, PlanFeature and OrganisationFeatureOverride.
-- ---------------------------------------------------------------------------
CREATE FUNCTION app_check_entitlement_value(
  feature_type "FeatureType", enabled boolean, lim bigint, unlimited boolean, config jsonb
) RETURNS void
  LANGUAGE plpgsql IMMUTABLE
  AS $$
  BEGIN
    IF lim IS NOT NULL AND lim < 0 THEN
      RAISE EXCEPTION 'entitlement limit must be >= 0' USING ERRCODE = 'check_violation';
    END IF;
    IF feature_type = 'BOOLEAN' THEN
      IF lim IS NOT NULL OR unlimited OR config IS NOT NULL THEN
        RAISE EXCEPTION 'BOOLEAN entitlements take no limit or config' USING ERRCODE = 'check_violation';
      END IF;
    ELSIF feature_type = 'LIMIT' THEN
      IF config IS NOT NULL THEN
        RAISE EXCEPTION 'LIMIT entitlements take no config' USING ERRCODE = 'check_violation';
      END IF;
      IF enabled AND ((lim IS NOT NULL) = unlimited) THEN
        RAISE EXCEPTION 'an enabled LIMIT entitlement needs exactly one of limit or unlimited'
          USING ERRCODE = 'check_violation';
      END IF;
      IF NOT enabled AND (lim IS NOT NULL OR unlimited) THEN
        RAISE EXCEPTION 'a disabled LIMIT entitlement takes no limit' USING ERRCODE = 'check_violation';
      END IF;
    ELSIF feature_type = 'CONFIGURATION' THEN
      IF lim IS NOT NULL OR unlimited THEN
        RAISE EXCEPTION 'CONFIGURATION entitlements take no limit' USING ERRCODE = 'check_violation';
      END IF;
      IF enabled AND (config IS NULL OR jsonb_typeof(config) <> 'object') THEN
        RAISE EXCEPTION 'an enabled CONFIGURATION entitlement needs a JSON object'
          USING ERRCODE = 'check_violation';
      END IF;
      IF config IS NOT NULL AND jsonb_typeof(config) <> 'object' THEN
        RAISE EXCEPTION 'entitlement config must be a JSON object' USING ERRCODE = 'check_violation';
      END IF;
    END IF;
  END
  $$;

CREATE FUNCTION app_check_feature_default() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
  BEGIN
    PERFORM app_check_entitlement_value(NEW.type, NEW."defaultEnabled", NEW."defaultLimit",
      NEW."defaultUnlimited", NEW."defaultConfig");
    RETURN NEW;
  END
  $$;

-- SECURITY DEFINER so the feature type is visible whichever role writes.
CREATE FUNCTION app_check_granted_entitlement() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = public, pg_temp
  AS $$
  DECLARE
    ftype "FeatureType";
  BEGIN
    SELECT type INTO ftype FROM "Feature" WHERE id = NEW."featureId";
    IF ftype IS NULL THEN
      RAISE EXCEPTION 'unknown feature' USING ERRCODE = 'foreign_key_violation';
    END IF;
    PERFORM app_check_entitlement_value(ftype, NEW.enabled, NEW."limit", NEW.unlimited, NEW.config);
    RETURN NEW;
  END
  $$;

REVOKE ALL ON FUNCTION app_check_entitlement_value("FeatureType", boolean, bigint, boolean, jsonb),
  app_check_feature_default(), app_check_granted_entitlement() FROM PUBLIC;

CREATE TRIGGER "Feature_check_default" BEFORE INSERT OR UPDATE ON "Feature"
  FOR EACH ROW EXECUTE FUNCTION app_check_feature_default();
CREATE TRIGGER "PlanFeature_check_value" BEFORE INSERT OR UPDATE ON "PlanFeature"
  FOR EACH ROW EXECUTE FUNCTION app_check_granted_entitlement();
CREATE TRIGGER "OrganisationFeatureOverride_check_value" BEFORE INSERT OR UPDATE ON "OrganisationFeatureOverride"
  FOR EACH ROW EXECUTE FUNCTION app_check_granted_entitlement();

-- ---------------------------------------------------------------------------
-- 2.2 Reference features. Keys are the FeatureKey union in
-- packages/entitlements (a test asserts parity). Defaults are the system
-- default: the floor for organisations without an entitling subscription.
-- Plans and plan features are business data loaded by `pnpm db:seed`.
-- ---------------------------------------------------------------------------
INSERT INTO "Feature" (id, key, name, description, type, "sortOrder",
  "defaultEnabled", "defaultLimit", "defaultUnlimited", "defaultConfig") VALUES
  (gen_random_uuid(), 'store_count', 'Stores', 'Stores that are not archived.', 'LIMIT', 10, true, 1, false, NULL),
  (gen_random_uuid(), 'staff_accounts', 'Team members', 'Members of the organisation, including the owner.', 'LIMIT', 20, true, 1, false, NULL),
  (gen_random_uuid(), 'product_limit', 'Products', 'Products that are not archived.', 'LIMIT', 30, true, 25, false, NULL),
  (gen_random_uuid(), 'media_storage', 'Media storage', 'Media library storage in bytes.', 'LIMIT', 40, true, 1073741824, false, NULL),
  (gen_random_uuid(), 'custom_domain', 'Custom domains', 'Serve stores on your own domain.', 'BOOLEAN', 50, false, NULL, false, NULL),
  (gen_random_uuid(), 'visual_builder', 'Page builder', 'Design pages visually.', 'BOOLEAN', 60, true, NULL, false, NULL),
  (gen_random_uuid(), 'advanced_builder', 'Advanced page builder', 'Advanced layout and interaction components.', 'BOOLEAN', 70, false, NULL, false, NULL),
  (gen_random_uuid(), 'premium_themes', 'Premium themes', 'Install premium themes.', 'BOOLEAN', 80, false, NULL, false, NULL),
  (gen_random_uuid(), 'analytics', 'Analytics', 'Store analytics and reports.', 'CONFIGURATION', 90, false, NULL, false, NULL),
  (gen_random_uuid(), 'discounts', 'Discounts', 'Discount codes and automatic discounts.', 'BOOLEAN', 100, false, NULL, false, NULL),
  (gen_random_uuid(), 'abandoned_cart', 'Abandoned cart recovery', 'Recover abandoned checkouts.', 'BOOLEAN', 110, false, NULL, false, NULL),
  (gen_random_uuid(), 'api_access', 'API access', 'Use the Storevia API with API keys.', 'BOOLEAN', 120, false, NULL, false, NULL),
  (gen_random_uuid(), 'webhooks', 'Webhooks', 'Send events to your own endpoints.', 'BOOLEAN', 130, false, NULL, false, NULL),
  (gen_random_uuid(), 'custom_code', 'Custom code', 'Add custom code to storefront pages.', 'BOOLEAN', 140, false, NULL, false, NULL),
  (gen_random_uuid(), 'advanced_permissions', 'Advanced permissions', 'Store-limited staff access.', 'BOOLEAN', 150, false, NULL, false, NULL),
  (gen_random_uuid(), 'export', 'Data export', 'Export your data.', 'BOOLEAN', 160, true, NULL, false, NULL),
  (gen_random_uuid(), 'priority_support', 'Priority support', 'Faster responses from Storevia support.', 'BOOLEAN', 170, false, NULL, false, NULL);

-- ---------------------------------------------------------------------------
-- 2.3 CHECK constraints and partial unique indexes (erd.md §6).
-- ---------------------------------------------------------------------------
ALTER TABLE "Plan"
  ADD CONSTRAINT "Plan_key_format" CHECK (key ~ '^[a-z][a-z0-9_]{1,39}$'),
  ADD CONSTRAINT "Plan_name_length" CHECK (char_length(btrim(name)) BETWEEN 1 AND 60),
  ADD CONSTRAINT "Plan_trial_days_range" CHECK ("trialDays" BETWEEN 0 AND 365);
ALTER TABLE "Feature"
  ADD CONSTRAINT "Feature_key_format" CHECK (key ~ '^[a-z][a-z0-9_]{1,39}$');
ALTER TABLE "PlanPrice"
  ADD CONSTRAINT "PlanPrice_amount_non_negative" CHECK (amount >= 0),
  ADD CONSTRAINT "PlanPrice_currency_format" CHECK (currency ~ '^[A-Z]{3}$');
CREATE UNIQUE INDEX "PlanPrice_one_active_per_interval_currency"
  ON "PlanPrice" ("planId", "interval", currency) WHERE active;

ALTER TABLE "OrganisationFeatureOverride"
  ADD CONSTRAINT "OrganisationFeatureOverride_reason_length" CHECK (char_length(btrim(reason)) BETWEEN 3 AND 500);

ALTER TABLE "Subscription"
  ADD CONSTRAINT "Subscription_source_provider" CHECK (
    (source = 'MANUAL' AND provider IS NULL AND "providerSubscriptionId" IS NULL)
    OR (source = 'MOCK' AND provider = 'MOCK' AND "providerSubscriptionId" IS NOT NULL)
    OR (source = 'PAYMENT_PROVIDER' AND provider IN ('RAZORPAY', 'STRIPE') AND "providerSubscriptionId" IS NOT NULL)
  ),
  ADD CONSTRAINT "Subscription_trial_dates" CHECK (
    (status <> 'TRIAL' OR "trialEndsAt" IS NOT NULL)
    AND ("trialStartsAt" IS NULL OR "trialEndsAt" IS NULL OR "trialStartsAt" < "trialEndsAt")
  ),
  ADD CONSTRAINT "Subscription_past_due_dates" CHECK (
    status <> 'PAST_DUE' OR ("pastDueSince" IS NOT NULL AND "graceEndsAt" IS NOT NULL)
  ),
  ADD CONSTRAINT "Subscription_cancelled_dates" CHECK (
    status <> 'CANCELLED' OR ("cancelledAt" IS NOT NULL AND "expiresAt" IS NOT NULL)
  ),
  ADD CONSTRAINT "Subscription_expired_dates" CHECK (status <> 'EXPIRED' OR "endedAt" IS NOT NULL),
  ADD CONSTRAINT "Subscription_period_order" CHECK (
    "currentPeriodStart" IS NULL OR "currentPeriodEnd" IS NULL OR "currentPeriodStart" < "currentPeriodEnd"
  );
CREATE UNIQUE INDEX "Subscription_one_live_per_organisation"
  ON "Subscription" ("organisationId") WHERE status <> 'EXPIRED';

ALTER TABLE "SubscriptionEvent"
  ADD CONSTRAINT "SubscriptionEvent_reason_length" CHECK (reason IS NULL OR char_length(reason) <= 500),
  ADD CONSTRAINT "SubscriptionEvent_note_length" CHECK (note IS NULL OR char_length(note) <= 2000);

ALTER TABLE "BillingWebhookEvent"
  ADD CONSTRAINT "BillingWebhookEvent_attempts_non_negative" CHECK (attempts >= 0);

ALTER TABLE "UsageCounter"
  ADD CONSTRAINT "UsageCounter_value_non_negative" CHECK (value >= 0);

-- ---------------------------------------------------------------------------
-- 2.4 Tenant ownership columns are immutable (function from the M1 migration).
-- SubscriptionEvent is append-only: nobody but the owner may UPDATE/DELETE.
-- ---------------------------------------------------------------------------
CREATE TRIGGER "Subscription_immutable_owner" BEFORE UPDATE ON "Subscription"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "OrganisationFeatureOverride_immutable_owner" BEFORE UPDATE ON "OrganisationFeatureOverride"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "UsageCounter_immutable_owner" BEFORE UPDATE ON "UsageCounter"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "BillingCustomer_immutable_owner" BEFORE UPDATE ON "BillingCustomer"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();

-- ---------------------------------------------------------------------------
-- 2.5 Row-level security for organisation-scoped billing tables.
-- ---------------------------------------------------------------------------
ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Subscription"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "SubscriptionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SubscriptionEvent" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SubscriptionEvent"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "OrganisationFeatureOverride" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganisationFeatureOverride" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "OrganisationFeatureOverride"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "UsageCounter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UsageCounter" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "UsageCounter"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "BillingCustomer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BillingCustomer" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "BillingCustomer"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "BillingWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BillingWebhookEvent" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "BillingWebhookEvent"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

-- ---------------------------------------------------------------------------
-- 2.6 Grants (ADR-0022 §8). Nothing to PUBLIC.
-- ---------------------------------------------------------------------------

-- Application role: reads the catalogue and its own organisation's
-- subscription and overrides (not the staff reason/author columns); maintains
-- its own usage counters. It can never write subscriptions, events or
-- overrides: merchants have no path to change their plan.
GRANT SELECT ON "Plan", "PlanPrice", "Feature", "PlanFeature" TO storevia_app;
GRANT SELECT ON "Subscription" TO storevia_app;
GRANT SELECT (id, "organisationId", "featureId", enabled, "limit", unlimited, config, "expiresAt")
  ON "OrganisationFeatureOverride" TO storevia_app;
GRANT SELECT, INSERT ON "UsageCounter" TO storevia_app;
GRANT UPDATE (value, "updatedAt") ON "UsageCounter" TO storevia_app;

-- System role: webhook pipeline and expiry sweep (packages/billing).
GRANT SELECT ON "Plan", "PlanPrice", "Feature", "PlanFeature" TO storevia_system;
GRANT SELECT, INSERT ON "Subscription" TO storevia_system;
GRANT UPDATE ("planId", status, "billingInterval", "startedAt", "trialStartsAt", "trialEndsAt",
  "currentPeriodStart", "currentPeriodEnd", "expiresAt", "cancelledAt", "pastDueSince",
  "graceEndsAt", "endedAt", "providerSyncedAt", "updatedAt") ON "Subscription" TO storevia_system;
GRANT INSERT ON "SubscriptionEvent" TO storevia_system;
GRANT SELECT ON "BillingCustomer" TO storevia_system;
GRANT SELECT, INSERT ON "BillingWebhookEvent" TO storevia_system;
GRANT UPDATE (status, "organisationId", attempts, outcome, "lastError", "processedAt")
  ON "BillingWebhookEvent" TO storevia_system;

-- Platform-admin role: reads everything billing-related; writes only what
-- audited staff actions need.
GRANT SELECT ON "Plan", "PlanPrice", "Feature", "PlanFeature", "Subscription", "SubscriptionEvent",
  "OrganisationFeatureOverride", "UsageCounter", "BillingCustomer", "BillingWebhookEvent"
  TO storevia_platform;
GRANT INSERT ON "Subscription" TO storevia_platform;
GRANT UPDATE ("planId", status, "billingInterval", "startedAt", "trialStartsAt", "trialEndsAt",
  "currentPeriodStart", "currentPeriodEnd", "expiresAt", "cancelledAt", "pastDueSince",
  "graceEndsAt", "endedAt", "updatedAt") ON "Subscription" TO storevia_platform;
GRANT INSERT ON "SubscriptionEvent" TO storevia_platform;
GRANT INSERT, DELETE ON "OrganisationFeatureOverride" TO storevia_platform;
GRANT UPDATE (enabled, "limit", unlimited, config, reason, "expiresAt", "updatedById", "updatedAt")
  ON "OrganisationFeatureOverride" TO storevia_platform;
GRANT INSERT ON "UsageCounter" TO storevia_platform;
GRANT UPDATE (value, "updatedAt") ON "UsageCounter" TO storevia_platform;
GRANT INSERT ON "BillingCustomer" TO storevia_platform;

-- ---------------------------------------------------------------------------
-- 2.7 Backfill gauge counters for organisations that existed before M2.
-- ---------------------------------------------------------------------------
INSERT INTO "UsageCounter" ("organisationId", "featureId", "scopeKey", period, value, "updatedAt")
SELECT o.id, f.id, '', 'all',
  (SELECT count(*) FROM "Store" s WHERE s."organisationId" = o.id AND s.status <> 'ARCHIVED'),
  CURRENT_TIMESTAMP
FROM "Organisation" o CROSS JOIN "Feature" f
WHERE f.key = 'store_count';

INSERT INTO "UsageCounter" ("organisationId", "featureId", "scopeKey", period, value, "updatedAt")
SELECT o.id, f.id, '', 'all',
  (SELECT count(*) FROM "Membership" m WHERE m."organisationId" = o.id),
  CURRENT_TIMESTAMP
FROM "Organisation" o CROSS JOIN "Feature" f
WHERE f.key = 'staff_accounts';
