-- Milestone 2.5: periodic job scheduler for apps/worker (ADR-0023).
-- Part 1 is generated by `prisma migrate diff`; part 2 adds CHECKs and grants.
-- storevia_worker is created by infrastructure / `pnpm db:setup` beforehand.

-- =============================================================================
-- Part 1: tables (generated)
-- =============================================================================
-- CreateEnum
CREATE TYPE "JobRunStatus" AS ENUM ('RUNNING', 'SUCCEEDED', 'FAILED');

-- CreateTable
CREATE TABLE "ScheduledJob" (
    "name" TEXT NOT NULL,
    "intervalSeconds" INTEGER NOT NULL,
    "slot" TIMESTAMPTZ(3) NOT NULL,
    "nextRunAt" TIMESTAMPTZ(3) NOT NULL,
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "lockedBy" TEXT,
    "lockedUntil" TIMESTAMPTZ(3),
    "lastStartedAt" TIMESTAMPTZ(3),
    "lastFinishedAt" TIMESTAMPTZ(3),
    "lastStatus" "JobRunStatus",
    "consecutiveFailures" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ScheduledJob_pkey" PRIMARY KEY ("name")
);

-- CreateTable
CREATE TABLE "JobRun" (
    "id" UUID NOT NULL,
    "jobName" TEXT NOT NULL,
    "slot" TIMESTAMPTZ(3) NOT NULL,
    "attempt" INTEGER NOT NULL,
    "workerId" TEXT NOT NULL,
    "status" "JobRunStatus" NOT NULL,
    "startedAt" TIMESTAMPTZ(3) NOT NULL,
    "finishedAt" TIMESTAMPTZ(3),
    "result" JSONB,
    "error" TEXT,

    CONSTRAINT "JobRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ScheduledJob_nextRunAt_idx" ON "ScheduledJob"("nextRunAt");

-- CreateIndex
CREATE INDEX "JobRun_jobName_startedAt_idx" ON "JobRun"("jobName", "startedAt");

-- CreateIndex
CREATE UNIQUE INDEX "JobRun_jobName_slot_attempt_key" ON "JobRun"("jobName", "slot", "attempt");

-- AddForeignKey
ALTER TABLE "JobRun" ADD CONSTRAINT "JobRun_jobName_fkey" FOREIGN KEY ("jobName") REFERENCES "ScheduledJob"("name") ON DELETE CASCADE ON UPDATE CASCADE;


-- =============================================================================
-- Part 2: hand-written
-- =============================================================================
ALTER TABLE "ScheduledJob"
  ADD CONSTRAINT "ScheduledJob_name_format" CHECK (name ~ '^[a-z][a-z0-9_.-]{2,80}$'),
  ADD CONSTRAINT "ScheduledJob_interval_positive" CHECK ("intervalSeconds" > 0),
  ADD CONSTRAINT "ScheduledJob_attempt_non_negative" CHECK (attempt >= 0),
  ADD CONSTRAINT "ScheduledJob_failures_non_negative" CHECK ("consecutiveFailures" >= 0);
ALTER TABLE "JobRun"
  ADD CONSTRAINT "JobRun_attempt_positive" CHECK (attempt >= 1),
  ADD CONSTRAINT "JobRun_error_length" CHECK (error IS NULL OR char_length(error) <= 500);

-- Worker role (BYPASSRLS, narrow): its own job tables, plus what usage
-- reconciliation reads (organisations, stores, memberships) and writes
-- (usage counters, SYSTEM audit entries). The expiry job uses storevia_billing.
GRANT USAGE ON SCHEMA public TO storevia_worker;
GRANT SELECT, INSERT, UPDATE ON "ScheduledJob", "JobRun" TO storevia_worker;
GRANT SELECT (id, status) ON "Organisation" TO storevia_worker;
GRANT SELECT (id, "organisationId", status) ON "Store" TO storevia_worker;
GRANT SELECT (id, "organisationId") ON "Membership" TO storevia_worker;
GRANT SELECT (id, key) ON "Feature" TO storevia_worker;
GRANT SELECT, INSERT ON "UsageCounter" TO storevia_worker;
GRANT UPDATE (value, "updatedAt") ON "UsageCounter" TO storevia_worker;
GRANT INSERT ON "AuditLog" TO storevia_worker;

-- Platform-admin shows job health read-only.
GRANT SELECT ON "ScheduledJob", "JobRun" TO storevia_platform;
