-- Milestone 1: identity, tenancy and stores (ADR-0020).
-- Part 1 is generated by `prisma migrate diff`; part 2 adds what Prisma cannot
-- express. Roles are created by infrastructure (`pnpm db:setup` locally/CI,
-- IaC in production) before this migration runs; see 03-tenancy.md §5.3.

CREATE EXTENSION IF NOT EXISTS citext;

-- =============================================================================
-- Part 1: tables (generated)
-- =============================================================================
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'DISABLED');

-- CreateEnum
CREATE TYPE "SessionRealm" AS ENUM ('DASHBOARD', 'PLATFORM');

-- CreateEnum
CREATE TYPE "PlatformRole" AS ENUM ('SUPER_ADMIN', 'OPERATIONS', 'SUPPORT', 'BILLING', 'READ_ONLY');

-- CreateEnum
CREATE TYPE "OrganisationStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'PENDING_DELETION', 'DELETED');

-- CreateEnum
CREATE TYPE "MemberRole" AS ENUM ('OWNER', 'ADMIN', 'STORE_MANAGER', 'DESIGNER', 'CATALOGUE_MANAGER', 'ORDER_MANAGER', 'MARKETING', 'SUPPORT', 'VIEWER');

-- CreateEnum
CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "StoreStatus" AS ENUM ('DRAFT', 'ACTIVE', 'SUSPENDED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "DomainType" AS ENUM ('PLATFORM_SUBDOMAIN', 'CUSTOM');

-- CreateEnum
CREATE TYPE "DomainStatus" AS ENUM ('PENDING', 'VERIFYING', 'ACTIVE', 'FAILED');

-- CreateEnum
CREATE TYPE "AuditActorType" AS ENUM ('USER', 'PLATFORM_STAFF', 'API_KEY', 'APP', 'SYSTEM');

-- CreateTable
CREATE TABLE "User" (
    "id" UUID NOT NULL,
    "email" CITEXT NOT NULL,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "name" TEXT NOT NULL,
    "image" TEXT,
    "locale" TEXT NOT NULL DEFAULT 'en',
    "timezone" TEXT NOT NULL DEFAULT 'UTC',
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,
    "deletedAt" TIMESTAMPTZ(3),

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "providerId" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "passwordHash" TEXT,
    "accessTokenEnc" TEXT,
    "refreshTokenEnc" TEXT,
    "idTokenEnc" TEXT,
    "accessTokenExpiresAt" TIMESTAMPTZ(3),
    "refreshTokenExpiresAt" TIMESTAMPTZ(3),
    "scope" TEXT,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "token" TEXT NOT NULL,
    "realm" "SessionRealm" NOT NULL DEFAULT 'DASHBOARD',
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "mfaVerifiedAt" TIMESTAMPTZ(3),
    "reauthenticatedAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Verification" (
    "id" UUID NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Verification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RateLimit" (
    "id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL,
    "lastRequest" BIGINT NOT NULL,

    CONSTRAINT "RateLimit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlatformStaff" (
    "userId" UUID NOT NULL,
    "role" "PlatformRole" NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "PlatformStaff_pkey" PRIMARY KEY ("userId")
);

-- CreateTable
CREATE TABLE "Organisation" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "status" "OrganisationStatus" NOT NULL DEFAULT 'ACTIVE',
    "billingEmail" TEXT,
    "country" CHAR(2),
    "createdById" UUID,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,
    "suspendedAt" TIMESTAMPTZ(3),
    "deletedAt" TIMESTAMPTZ(3),

    CONSTRAINT "Organisation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Membership" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "role" "MemberRole" NOT NULL,
    "status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE',
    "allStores" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Membership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MembershipStoreAccess" (
    "membershipId" UUID NOT NULL,
    "storeId" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MembershipStoreAccess_pkey" PRIMARY KEY ("membershipId","storeId")
);

-- CreateTable
CREATE TABLE "Invitation" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "email" CITEXT NOT NULL,
    "role" "MemberRole" NOT NULL,
    "tokenHash" TEXT NOT NULL,
    "status" "InvitationStatus" NOT NULL DEFAULT 'PENDING',
    "expiresAt" TIMESTAMPTZ(3) NOT NULL,
    "invitedById" UUID NOT NULL,
    "acceptedById" UUID,
    "acceptedAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Invitation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Store" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" "StoreStatus" NOT NULL DEFAULT 'DRAFT',
    "currency" CHAR(3) NOT NULL,
    "locale" TEXT NOT NULL,
    "timezone" TEXT NOT NULL,
    "country" CHAR(2) NOT NULL,
    "logoMediaId" UUID,
    "faviconMediaId" UUID,
    "contactEmail" TEXT,
    "supportEmail" TEXT,
    "nextOrderNumber" INTEGER NOT NULL DEFAULT 1001,
    "suspendedAt" TIMESTAMPTZ(3),
    "suspensionReason" TEXT,
    "archivedAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "Store_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StoreDomain" (
    "id" UUID NOT NULL,
    "organisationId" UUID NOT NULL,
    "storeId" UUID NOT NULL,
    "hostname" TEXT NOT NULL,
    "type" "DomainType" NOT NULL,
    "status" "DomainStatus" NOT NULL DEFAULT 'PENDING',
    "verificationToken" TEXT NOT NULL,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "verifiedAt" TIMESTAMPTZ(3),
    "lastCheckedAt" TIMESTAMPTZ(3),
    "failureReason" TEXT,
    "providerRef" TEXT,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "StoreDomain_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" UUID NOT NULL,
    "organisationId" UUID,
    "storeId" UUID,
    "actorType" "AuditActorType" NOT NULL,
    "actorId" UUID,
    "onBehalfOfUserId" UUID,
    "action" TEXT NOT NULL,
    "entityType" TEXT,
    "entityId" UUID,
    "metadata" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "requestId" TEXT,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id","createdAt")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "Account_userId_idx" ON "Account"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Account_providerId_accountId_key" ON "Account"("providerId", "accountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_token_key" ON "Session"("token");

-- CreateIndex
CREATE INDEX "Session_userId_idx" ON "Session"("userId");

-- CreateIndex
CREATE INDEX "Session_expiresAt_idx" ON "Session"("expiresAt");

-- CreateIndex
CREATE INDEX "Verification_identifier_idx" ON "Verification"("identifier");

-- CreateIndex
CREATE INDEX "Verification_expiresAt_idx" ON "Verification"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "RateLimit_key_key" ON "RateLimit"("key");

-- CreateIndex
CREATE INDEX "Organisation_createdById_idx" ON "Organisation"("createdById");

-- CreateIndex
CREATE INDEX "Membership_userId_idx" ON "Membership"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Membership_organisationId_userId_key" ON "Membership"("organisationId", "userId");

-- CreateIndex
CREATE UNIQUE INDEX "Membership_id_organisationId_key" ON "Membership"("id", "organisationId");

-- CreateIndex
CREATE INDEX "MembershipStoreAccess_storeId_idx" ON "MembershipStoreAccess"("storeId");

-- CreateIndex
CREATE UNIQUE INDEX "Invitation_tokenHash_key" ON "Invitation"("tokenHash");

-- CreateIndex
CREATE INDEX "Invitation_organisationId_status_idx" ON "Invitation"("organisationId", "status");

-- CreateIndex
CREATE INDEX "Invitation_invitedById_idx" ON "Invitation"("invitedById");

-- CreateIndex
CREATE INDEX "Invitation_acceptedById_idx" ON "Invitation"("acceptedById");

-- CreateIndex
CREATE UNIQUE INDEX "Store_slug_key" ON "Store"("slug");

-- CreateIndex
CREATE INDEX "Store_organisationId_idx" ON "Store"("organisationId");

-- CreateIndex
CREATE UNIQUE INDEX "Store_id_organisationId_key" ON "Store"("id", "organisationId");

-- CreateIndex
CREATE UNIQUE INDEX "StoreDomain_hostname_key" ON "StoreDomain"("hostname");

-- CreateIndex
CREATE INDEX "StoreDomain_storeId_idx" ON "StoreDomain"("storeId");

-- CreateIndex
CREATE INDEX "StoreDomain_status_lastCheckedAt_idx" ON "StoreDomain"("status", "lastCheckedAt");

-- CreateIndex
CREATE INDEX "AuditLog_organisationId_createdAt_idx" ON "AuditLog"("organisationId", "createdAt");

-- CreateIndex
CREATE INDEX "AuditLog_storeId_createdAt_idx" ON "AuditLog"("storeId", "createdAt");

-- CreateIndex
CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt");

-- CreateIndex
CREATE INDEX "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType", "entityId");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlatformStaff" ADD CONSTRAINT "PlatformStaff_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Organisation" ADD CONSTRAINT "Organisation_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MembershipStoreAccess" ADD CONSTRAINT "MembershipStoreAccess_membershipId_organisationId_fkey" FOREIGN KEY ("membershipId", "organisationId") REFERENCES "Membership"("id", "organisationId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MembershipStoreAccess" ADD CONSTRAINT "MembershipStoreAccess_storeId_organisationId_fkey" FOREIGN KEY ("storeId", "organisationId") REFERENCES "Store"("id", "organisationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_invitedById_fkey" FOREIGN KEY ("invitedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_acceptedById_fkey" FOREIGN KEY ("acceptedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Store" ADD CONSTRAINT "Store_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StoreDomain" ADD CONSTRAINT "StoreDomain_storeId_organisationId_fkey" FOREIGN KEY ("storeId", "organisationId") REFERENCES "Store"("id", "organisationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- =============================================================================
-- Part 2: constraints, helpers, row-level security and grants (hand-written)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 2.1 RLS context helpers. Values are set transaction-locally by withTenant();
-- NULLIF(..., '') because a reset transaction-local setting reads as ''.
-- ---------------------------------------------------------------------------
CREATE FUNCTION app_current_org() RETURNS uuid
  LANGUAGE sql STABLE
  AS $$ SELECT NULLIF(current_setting('app.organisation_id', true), '')::uuid $$;

CREATE FUNCTION app_current_store() RETURNS uuid
  LANGUAGE sql STABLE
  AS $$ SELECT NULLIF(current_setting('app.store_id', true), '')::uuid $$;

CREATE FUNCTION app_current_user() RETURNS uuid
  LANGUAGE sql STABLE
  AS $$ SELECT NULLIF(current_setting('app.user_id', true), '')::uuid $$;

-- Organisations in which the current user has an ACTIVE membership. SECURITY
-- DEFINER (owner has BYPASSRLS) so policies that call it cannot recurse.
CREATE FUNCTION app_member_organisation_ids() RETURNS SETOF uuid
  LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path = public, pg_temp
  AS $$
    SELECT "organisationId" FROM "Membership"
    WHERE "userId" = app_current_user() AND status = 'ACTIVE'
  $$;

REVOKE ALL ON FUNCTION app_current_org(), app_current_store(), app_current_user(),
  app_member_organisation_ids() FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- 2.2 Tenant ownership columns are immutable.
-- ---------------------------------------------------------------------------
CREATE FUNCTION app_forbid_owner_change() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
  BEGIN
    IF (to_jsonb(NEW) ->> 'organisationId') IS DISTINCT FROM (to_jsonb(OLD) ->> 'organisationId')
      OR (to_jsonb(NEW) ->> 'storeId') IS DISTINCT FROM (to_jsonb(OLD) ->> 'storeId')
      OR (to_jsonb(NEW) ->> 'userId') IS DISTINCT FROM (to_jsonb(OLD) ->> 'userId') THEN
      RAISE EXCEPTION 'ownership columns of % are immutable', TG_TABLE_NAME
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
  END
  $$;

CREATE TRIGGER "Membership_immutable_owner" BEFORE UPDATE ON "Membership"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "MembershipStoreAccess_immutable_owner" BEFORE UPDATE ON "MembershipStoreAccess"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "Invitation_immutable_owner" BEFORE UPDATE ON "Invitation"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "Store_immutable_owner" BEFORE UPDATE ON "Store"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "StoreDomain_immutable_owner" BEFORE UPDATE ON "StoreDomain"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();
CREATE TRIGGER "AuditLog_immutable_owner" BEFORE UPDATE ON "AuditLog"
  FOR EACH ROW EXECUTE FUNCTION app_forbid_owner_change();

-- ---------------------------------------------------------------------------
-- 2.3 Partial unique indexes and CHECK constraints (erd.md §6).
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "Membership_one_owner_per_organisation"
  ON "Membership" ("organisationId") WHERE role = 'OWNER';
CREATE UNIQUE INDEX "Invitation_one_pending_per_email"
  ON "Invitation" ("organisationId", email) WHERE status = 'PENDING';
CREATE UNIQUE INDEX "StoreDomain_one_primary_per_store"
  ON "StoreDomain" ("storeId") WHERE "isPrimary";

ALTER TABLE "Organisation"
  ADD CONSTRAINT "Organisation_name_length" CHECK (char_length(btrim(name)) BETWEEN 1 AND 100),
  ADD CONSTRAINT "Organisation_country_format" CHECK (country IS NULL OR country ~ '^[A-Z]{2}$');
ALTER TABLE "Store"
  ADD CONSTRAINT "Store_name_length" CHECK (char_length(btrim(name)) BETWEEN 1 AND 100),
  ADD CONSTRAINT "Store_slug_format" CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])$' AND slug !~ '--'),
  ADD CONSTRAINT "Store_currency_format" CHECK (currency ~ '^[A-Z]{3}$'),
  ADD CONSTRAINT "Store_country_format" CHECK (country ~ '^[A-Z]{2}$'),
  ADD CONSTRAINT "Store_next_order_number_positive" CHECK ("nextOrderNumber" > 0);
ALTER TABLE "StoreDomain"
  ADD CONSTRAINT "StoreDomain_hostname_format"
  CHECK (hostname = lower(hostname) AND hostname !~ '[:/\s]' AND hostname !~ '\.$' AND char_length(hostname) <= 253);

-- ---------------------------------------------------------------------------
-- 2.4 Row-level security (03-tenancy.md §5.2). FORCE applies it to the table
-- owner as well; roles with BYPASSRLS (migrator, system, platform) skip it.
-- ---------------------------------------------------------------------------
ALTER TABLE "Organisation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organisation" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Organisation"
  USING (id = app_current_org()) WITH CHECK (id = app_current_org());
CREATE POLICY member_read ON "Organisation" FOR SELECT
  USING (id IN (SELECT app_member_organisation_ids()));

ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Membership"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());
CREATE POLICY self_read ON "Membership" FOR SELECT
  USING ("userId" = app_current_user());

ALTER TABLE "MembershipStoreAccess" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MembershipStoreAccess" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "MembershipStoreAccess"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "Invitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invitation" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Invitation"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

ALTER TABLE "Store" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Store" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Store"
  USING ("organisationId" = app_current_org() AND (app_current_store() IS NULL OR id = app_current_store()))
  WITH CHECK ("organisationId" = app_current_org() AND (app_current_store() IS NULL OR id = app_current_store()));
CREATE POLICY member_read ON "Store" FOR SELECT
  USING ("organisationId" IN (SELECT app_member_organisation_ids()));

ALTER TABLE "StoreDomain" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoreDomain" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "StoreDomain"
  USING ("organisationId" = app_current_org() AND (app_current_store() IS NULL OR "storeId" = app_current_store()))
  WITH CHECK ("organisationId" = app_current_org() AND (app_current_store() IS NULL OR "storeId" = app_current_store()));

ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "AuditLog"
  USING ("organisationId" = app_current_org()) WITH CHECK ("organisationId" = app_current_org());

-- Merchant identity is not tenant data, but the app role may read the current
-- user and the members of the current organisation (member lists) only.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
CREATE POLICY self_or_co_member_read ON "User" FOR SELECT
  USING (
    id = app_current_user()
    OR id IN (SELECT "userId" FROM "Membership" WHERE "organisationId" = app_current_org())
  );

-- ---------------------------------------------------------------------------
-- 2.5 Grants. Nothing is granted to PUBLIC. Prisma writes use RETURNING, so
-- roles that insert through Prisma `create` also need SELECT; audit writes use
-- `createMany` (no RETURNING) so INSERT alone is enough there.
-- ---------------------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO storevia_app, storevia_system, storevia_platform;

-- Application role (NOBYPASSRLS).
GRANT EXECUTE ON FUNCTION app_current_org(), app_current_store(), app_current_user(),
  app_member_organisation_ids() TO storevia_app;
GRANT SELECT, INSERT, UPDATE ON "Organisation" TO storevia_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "Membership", "MembershipStoreAccess" TO storevia_app;
GRANT SELECT, INSERT, UPDATE ON "Invitation", "Store" TO storevia_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "StoreDomain" TO storevia_app;
GRANT SELECT, INSERT ON "AuditLog" TO storevia_app;
GRANT SELECT (id, email, "emailVerified", name, image, locale, timezone, status) ON "User" TO storevia_app;
-- No privileges on Account, Session, Verification, RateLimit or PlatformStaff (ADR-0021).

-- System role (BYPASSRLS, narrow): packages/auth and invitation-token lookup.
GRANT SELECT, INSERT, UPDATE, DELETE ON "User", "Account", "Session", "Verification", "RateLimit"
  TO storevia_system;
GRANT SELECT ON "PlatformStaff" TO storevia_system;
GRANT SELECT ON "Invitation" TO storevia_system;
GRANT SELECT (id, name, status) ON "Organisation" TO storevia_system;
GRANT INSERT ON "AuditLog" TO storevia_system;

-- Platform-admin role (BYPASSRLS, read-only plus audit).
GRANT SELECT ON "Organisation", "Membership", "Store", "StoreDomain", "AuditLog", "PlatformStaff"
  TO storevia_platform;
GRANT SELECT (id, email, "emailVerified", name, status, "createdAt") ON "User" TO storevia_platform;
GRANT INSERT ON "AuditLog" TO storevia_platform;

-- Future: Store.logoMediaId / faviconMediaId get their composite same-store FKs
-- when MediaAsset is promoted (Milestone 3, erd.md §6).
